server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_disk?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    # 发送邮件的邮箱账号
    username: 2055126913@qq.com
    password: sytcuprjuvdiedia # 这是一个授权码，不是邮箱密码，切记不要泄露
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  # SQL初始化配置
  sql:
    init:
      mode: always
      encoding: UTF-8

  # 文件上传配置
  servlet:
    multipart:
    #  单个最大请求大小
      max-file-size: 500MB
      #  总最大请求大小（多个文件）
      max-request-size: 1000MB

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 自定义：网盘文件存储路径，启动时自动创建
# 默认使用当前目录下的 upload 文件夹，也可改为绝对路径如 E:/disk/upload/
disk:
  upload:
    path: E:/disk/upload/


# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# 跨域配置后续用代码配置，这里不用管
# cors:
#   mapping:
#     "/api/**":
#       allowedOrigins: "*"
#       allowedMethods: "*"
#       allowedHeaders: "*"
#       maxAge: 3600
#       allowCredentials: true
#